### PR TITLE
Develop attraction page

### PR DESCRIPTION
**Pull request by jackylailai**
I'm 賴杰聰
finished attraction
http://54.206.232.36:3000/
http://54.206.232.36:3000/attraction/10
thank you for your reviewing

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Separating lines should be 1px height with light grey color. And second one should not extend to full width in large devices.
2. Date input should be a date input element.

**Comment by jackylailai** [comment]
Finished the issues as mentioned above

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by jackylailai** [comment]
merge attraction

**Pull request merged**
