### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jackylailai**
老師麻煩您了，我是賴杰聰，discord：jkdd8484
 http://54.206.232.36:3000/api/attractions?page=1 
http://54.206.232.36:3000/api/attractions?page=0&keyword=劍潭 http://54.206.232.36:3000/api/attractions?page=0&keyword=北 http://54.206.232.36:3000/api/attraction/10
http://54.206.232.36:3000/api/mrts

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Page parameter of `/api/attraction` should start from 0. So http://54.206.232.36:3000/api/attractions?page=2&keyword=%E5%8C%97 and http://54.206.232.36:3000/api/attractions?page=5 should contain no data. http://54.206.232.36:3000/api/attractions?page=0 and http://54.206.232.36:3000/api/attractions?page=1 should be different.
2. `images` field of attraction should be a string array containing every image URLs. For example: ["Image URL 1", "Image URL 2", ...]. But yours is actually a string "['Image URL 1', 'Image URL 2', ...]"

Fix issues and re-request review.

**Comment by jackylailai** [comment]
After teacher viewing and tutoring, I have fulfilled all the requirements mentioned above.
Thank you so much for reviewing my code.
Please help me to check if it have been  completed.

**Comment by cwpeng** [comment]
Re-request review from top right corner in this page so that I can review for you.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
