### PR TITLE
Develop added frontend function

### PR DESCRIPTION
**Pull request by jackylailai**
Hi teacher,

I'm 賴杰聰,the url below is my website for homework.
http://54.206.232.36:3000

Thank you so much for reviewing!

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. There should have 2 pages if we search 北.
2. Aspect ratio of images should keep the same as original file in any size of devices.
3. There are left and right border in attraction boxes.
4. MRT list should have no available scrollbar, and we have to implement **scrolling animation effect** on it.

**Comment by jackylailai** [comment]
Finished the issues as mentioned above

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Avoid submition of search form after we press enter in search input.
2. If we search 北 multiple times, only first time can load second page, others cannot.

**Comment by jackylailai** [comment]
Finished the issues as mentioned second times

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by jackylailai** [comment]
[Develop added frontend function]

**Pull request merged**
